### ISSUE TITLE
[Website] can't be reached over IPv6

### ISSUE THREAD

**Issue by beerisgood** [davidesantangelo/feedirss-api#13]
Your website can't be opened over IPv6 connections. See: https://www.ssllabs.com/ssltest/analyze.html?d=feedi.me
> 2001-08d8-100f-f000-0000-0000-0000-0271.elastic-ssl.ui-r.com
Failed to communicate with the secure server 
>
> static.86.148.203.116.clients.your-server.de
Ready

**Comment by beerisgood** [comment]
7 months later and problem still exist.
Looks like no interest / project inactive

**Comment by davidesantangelo** [comment]
changed to api.feedirss.com https://www.ssllabs.com/ssltest/analyze.html?d=api.feedirss.com it works now!
